language: python
addons:
  ssh_known_hosts:
  - github.com
branches:
  only:
  - website
before_install:
  - openssl aes-256-cbc -K $encrypted_189e52c2c347_key -iv $encrypted_189e52c2c347_iv -in deploy_key.enc -out deploy_key -d
  - pip3 install --upgrade pip

deploy:
  provider: pages:git
  deploy_key: deploy_key
  target_branch: master
  keep_history: true
  edge:
    branch: master
  verbose: true
  skip_cleanup: true
install:
- pip3 install -r requirements.txt
script:
- python3 -m unittest discover tests
after_success:
  - chmod +x travis/push.sh
  - travis/push.sh
