language: python
addons:
  ssh_known_hosts:
  - github.com
git:
  url: git@github.com:arjunsavel/arjunsavel.github.io.git
  branch: master
  auth:
    type: ssh
    privateKey: deploy_key.enc
    sslVerify: true
  signature:
    name: Arjun Savel
    email: asavel@berkeley.edu
branches:
  only:
  - website
before_install:
  - openssl aes-256-cbc -K $encrypted_189e52c2c347_key -iv $encrypted_189e52c2c347_iv -in deploy_key.enc -out deploy_key -d
  - pip3 install --upgrade pip
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - chmod 600 deploy_key
  - eval $(ssh-agent -s)
  - ssh-add deploy_key

deploy:
  provider: script
  deploy_key: deploy_key
  target_branch: master
  keep_history: true
  edge:
    branch: master
  verbose: true
  skip_cleanup: true
install:
- pip3 install -r requirements.txt
script:
- python3 -m unittest discover tests
after_success:
  - chmod +x travis/build_CV.sh
  - chmod +x travis/push.sh
  - travis/build_CV.sh
  - travis/push.sh
