language: python
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_189e52c2c347_key -iv $encrypted_189e52c2c347_iv
  -in deploy_key.enc -out /home/travis/.dpl/deploy_key -d
deploy:
  provider: pages:git
  deploy_key: ~/.dpl/deploy_key
  edge:
    branch: master
  verbose: true
  skip_cleanup: true
jobs:
  include:
  - name: Python 3.7.4 on Xenial Linux
    python: 3.7.4
    before_install:
    - pip3 install --upgrade pip
install:
- pip3 install -r requirements.txt
script:
- python3 -m unittest discover tests
